Create backstage deployment configuration, add individual Dockerfiles…
kndpio/kndp pull request #106
Opened 2023-10-25 14:23 UTC by catalindev0ps

… for backend and frontend KNDP Backstage applications

2023-10-25 14:47 UTC, web7evgheni requested changes

2023-10-25 14:47 UTC, web7evgheni commented on .github/workflows/releases.yaml
> +        run: cat build.txt | xargs -I{} bash -c '[ -f {}/Dockerfile ] && docker build -t ${REGISTRY}/${{ github.repository }}/$(basename {}):0.1.0 -f {}/Dockerfile . && docker push ${REGISTRY}/${{ gi
@catalindev0ps Why version is hardcoded?

2023-10-25 14:47 UTC, web7evgheni commented on packages/backstage/charts/backstage-app/templates/deployment.yaml
> +	{{- with .Values.podLabels }}
@catalindev0ps Please fix formatting.

2023-10-25 14:47 UTC, web7evgheni commented on tsconfig.json
> +    "plugins/backstage/*/src"
@catalindev0ps we not have ./plugins directory

2023-10-25 14:47 UTC, web7evgheni commented on packages/backstage/backend/package.json
> -    "app": "link:../app",
@catalindev0ps Why you remove it? This is package of Yarn workspace

2023-10-25 15:00 UTC, catalindev0ps commented on packages/backstage/backend/package.json
> -    "app": "link:../app",
@web7evgheni otherwise the backend will build to the frontend

2023-10-25 15:45 UTC, web7evgheni commented on packages/backstage/backend/package.json
> -    "app": "link:../app",
@catalindev0ps Not clear what you mean.

2023-10-25 15:51 UTC, catalindev0ps commented on .github/workflows/releases.yaml
> +        run: cat build.txt | xargs -I{} bash -c '[ -f {}/Dockerfile ] && docker build -t ${REGISTRY}/${{ github.repository }}/$(basename {}):0.1.0 -f {}/Dockerfile . && docker push ${REGISTRY}/${{ gi
Backstage backend by default is engaged to build and serve the frontend, but now i modified both to build and serve individually

2023-10-26 12:25 UTC, web7evgheni requested changes

2023-10-26 12:25 UTC, web7evgheni commented on packages/backstage/charts/backstage-app/values.yaml
> +  name: APP_COFIG_app_baseUrl
@catalindev0ps Do you think just single config we will required to setup? Please make array

2023-10-26 12:25 UTC, web7evgheni commented on packages/backstage/charts/backstage-backend/templates/app-config-inject.yaml
@catalindev0ps After was integrated appConfig in values.yaml, we not use it anymore, not?

2023-10-26 14:42 UTC, web7evgheni approved these changes

2023-10-26 14:43 UTC, merged