add custom EntityProvider to create catalog backstage entities from k…
kndpio/kndp pull request #109
Opened 2023-10-30 14:42 UTC by ca7alindev

…ubernetes objects

2023-10-30 16:25 UTC, web7evgheni requested changes

2023-10-30 16:25 UTC, web7evgheni commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +    const defaultEndpoints = [ 'https://kubernetes.default.svc/apis/kndp.io/v1alpha1/releases' ];
@catalindev0ps No default endpoints, everything shall come from environment!!!

2023-10-30 16:25 UTC, web7evgheni commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +            "backstage.io/managed-by-origin-location": "file:../../../../catalog-info.yaml"
@catalindev0ps Why this is required?

2023-10-30 16:25 UTC, web7evgheni commented on packages/backstage/charts/backstage-backend/templates/deployment.yaml
> +          name: backstage-token
@catalindev0ps Use service account token. And if required add RBAC configuration for this service account for read all current API groups we have in KNDP

2023-10-31 08:32 UTC, catalindev0ps commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +            "backstage.io/managed-by-origin-location": "file:../../../../catalog-info.yaml"
got "catalog warn Entity 'component:default/release' does not have the annotation backstage.io/managed-by-location type=plugin entity=component:default/crossplane location=undefined" and without this annotations entity is not displayed in frontend

2023-10-31 09:43 UTC, web7evgheni requested changes

2023-10-31 09:43 UTC, web7evgheni commented on packages/backstage/charts/backstage-backend/templates/deployment.yaml
> +          name: backstage-token
@catalindev0ps This backstage-token still required?

2023-10-31 09:43 UTC, web7evgheni commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +      console.log(entity);
@catalindev0ps Remove console.log

2023-10-31 09:43 UTC, web7evgheni commented on packages/backstage/charts/backstage-backend/templates/rbac.yaml
> +    resources: ['releases']
@catalindev0ps  please use resources: ["*"] to be possible to access next resources types.

2023-10-31 09:43 UTC, web7evgheni commented on packages/backstage/charts/backstage-backend/templates/rbac.yaml
> +    verbs: ['get', 'list', 'watch', 'create', 'edit']
@catalindev0ps Please add delete also

2023-10-31 10:02 UTC, ca7alindev commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +      console.log(entity);
@web7evgheni yes, i think this "file:../../../..//catalog-info.yaml" should be replaced with the location from where EntityProvider fetch data, like "https://kubernetes.default.svc"

2023-10-31 10:03 UTC, ca7alindev commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +      console.log(entity);
As is explain in docs "The value of this annotation is a so called location reference string, that points to the source from which the entity was originally fetched."

2023-10-31 10:36 UTC, web7evgheni commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +      console.log(entity);
@ca7alindev Proof link please.

2023-10-31 10:45 UTC, ca7alindev commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +      console.log(entity);
https://backstage.io/docs/features/software-catalog/well-known-annotations/

2023-10-31 11:18 UTC, web7evgheni requested changes

2023-10-31 11:18 UTC, web7evgheni commented on packages/backstage/backend/src/plugins/EntityProvider.ts
> +      console.log(entity);
@ca7alindev Make it link to fetched URL, means k8s api.

2023-10-31 11:55 UTC, web7evgheni approved these changes

2023-10-31 11:55 UTC, merged