fix image building action for extract correct name from paths
kndpio/kndp pull request #118
Opened 2023-11-02 10:07 UTC by ca7alindev

2023-11-03 09:46 UTC, web7evgheni approved these changes

2023-11-03 09:47 UTC, web7evgheni requested changes

2023-11-03 09:47 UTC, web7evgheni commented on build.txt
@ca7alindev Please exclude this file

2023-11-03 09:47 UTC, web7evgheni commented on name
@ca7alindev Please exclude this file

2023-11-07 09:47 UTC, web7evgheni commented
@ca7alindev please remove files, i can't merge.

2023-11-07 11:17 UTC, ca7alindev commented on name
![image](https://github.com/kndpio/kndp/assets/90351697/b9c0748e-e2d2-40d8-8432-3f4f9a96ba0a)

2023-11-07 11:35 UTC, web7evgheni approved these changes

2023-11-07 11:35 UTC, merged