handle duplication of output on kndp create cmd
kndpio/kndp pull request #14
Opened 2024-02-05 15:45 UTC by ca7alindev

2024-02-06 08:51 UTC, web7evgheni requested changes

2024-02-06 08:51 UTC, web7evgheni commented on cmd/kndp/environment/create.go
> +			fmt.Println(line)
@ca7alindev Please try to configure kind to not display "fancy" messages, as i understood is possible by special environment variables, which says to kind, that terminal do not supports such kind of messages.

2024-02-06 10:46 UTC, web7evgheni commented
@ca7alindev Check this function, there possible to switch Kind output into different mode:
https://github.com/kubernetes-sigs/kind/blob/main/pkg/internal/env/term.go#L51

2024-02-06 11:27 UTC, web7evgheni commented
@ca7alindev How you did that?

2024-02-06 11:29 UTC, ca7alindev commented
@web7evgheni by setting some env variables as suggested in https://github.com/kubernetes-sigs/kind/blob/main/pkg/internal/env/term.go#L51

2024-02-06 11:34 UTC, web7evgheni commented
@ca7alindev How did you set envs?

2024-02-06 11:35 UTC, ca7alindev commented
@web7evgheni in terminal with export, like "export TERM=dumb", the output was changed in simpler one, but sill with double lines

2024-02-06 11:42 UTC, web7evgheni commented
@ca7alindev Do you think Go give your TTY environment variables to exec commands by default? :)

2024-02-09 08:18 UTC, web7evgheni approved these changes

2024-02-09 08:18 UTC, merged