Feature/144 meal composition with votes collector
kndpio/kndp pull request #146
Opened 2023-12-21 15:18 UTC by ca7alindev

2023-12-22 15:17 UTC, web7evgheni requested changes

2023-12-22 15:17 UTC, web7evgheni commented on packages/meal/slack-cronjob/main.go
> +	cmd := exec.Command("/usr/local/bin/kubectl", "get", "meal", mealName, "-o", "json")
@ca7alindev Please make use Go SDK for communicate with k8s.

2023-12-22 15:17 UTC, web7evgheni commented on packages/meal/slack-deployment/main.go
> +	cmd := exec.Command("kubectl", "get", "meal", mealName, "-o", "json")
@ca7alindev SDK?

2023-12-22 15:17 UTC, web7evgheni commented on packages/meal/slack-cronjob/main.go
> +func slackBot() {
@ca7alindev Simple name it  main, why you need function for call another function?

2023-12-27 11:37 UTC, ca7alindev commented
@web7evgheni please check this pr

2023-12-27 14:18 UTC, web7evgheni requested changes

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +									"host": "kndp.io",
@ca7alindev Make host to be provided from env.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +													"image": "ghcr.io/kndpio/kndp/slack-cronjob:0.1.0",
@ca7alindev Make image provided from env from helm chart.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +							"schedule": "*/15 * * * *",
@ca7alindev Make schecdule provided from env from helm chart.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +											"serviceAccountName": "meal-sa",
@ca7alindev Make SA provided from env from helm chart.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +				"name": "cronjob-object",
@ca7alindev Hardcoded.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +				"providerConfigRef": map[string]interface{}{"name": "kubernetes-provider"},
@ca7alindev Make providerConfigRef provided from env from helm chart.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +				"name": "deployment-object",
@ca7alindev Hardcoded

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +											"image": "ghcr.io/kndpio/kndp/slack-deployment:0.1.0",
@ca7alindev Make image provided from env from helm chart.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +									"serviceAccountName": "meal-sa",
@ca7alindev Make SA provided from env from helm chart.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +												{"configMapRef": map[string]interface{}{"name": "kndp-meal"}},
@ca7alindev Make CM provided from env from helm chart.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/function/fn.go
> +				"providerConfigRef": map[string]interface{}{"name": "kubernetes-provider"},
@ca7alindev Make PCR provided from env from helm chart.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/slack-cronjob/Dockerfile
@ca7alindev rename it to slack-notify, because it could because not just for cronjob

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/slack-cronjob/main.go
> +		Text:          "Do you want to order meal today? :poultry_leg:",
@ca7alindev please make this from env.

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/slack-deployment/Dockerfile
@ca7alindev Rename it to slack-collector

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/slack-deployment/main.go
> +		Text:          "Thank you",
@ca7alindev Make this from env

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/slack-deployment/main.go
> +	http.HandleFunc("/events-endpoint", func(w http.ResponseWriter, r *http.Request) {
@ca7alindev Make url to comes from env + default value

2023-12-27 14:18 UTC, web7evgheni commented on packages/meal/slack-deployment/main.go
> +	http.ListenAndServe(":3000", nil)
@ca7alindev Make port changeable by env + default value

2023-12-27 16:04 UTC, ca7alindev commented on .github/workflows/releases.yaml
> +      run: cat build.txt | xargs -I{} bash -c ' dirname $(find {} -name crossplane.yaml)' | xargs -I{} bash -c './crossplane xpkg build -f {} -o {}/$(basename {}) --embed-runtime-image ghcr.io/kndpio
@web7evgheni but that step before is not used just for ghcr.io/kndpio/kndp/function:0.1.0 image, is used to build all images from repo, but we need exactly this image "ghcr.io/kndpio/kndp/function:0.1.0" to embed the package and push it

2023-12-27 16:11 UTC, ca7alindev commented on packages/meal/function/fn.go
> +func readMealResource(dynamicClient dynamic.Interface, ctx context.Context, group, version, resource, namespace string) (string, error) {
@web7evgheni used "group, version, resource" to get data from Meal Object, i don't need other resources here

2023-12-28 11:53 UTC, web7evgheni commented on .github/workflows/releases.yaml
> +      run: cat build.txt | xargs -I{} bash -c ' dirname $(find {} -name crossplane.yaml)' | xargs -I{} bash -c './crossplane xpkg build -f {} -o {}/$(basename {}) --embed-runtime-image ghcr.io/kndpio
@ca7alindev You have to add current function Go app as runtime, not what you compiled one time?
I know that we need runtime for inject into it Crossplane package manifests, but function will not work with sources of function.
What's idea?

2023-12-28 11:59 UTC, web7evgheni requested changes
@ca7alindev Please resolve all issues, do not simple close them.

2023-12-28 11:59 UTC, web7evgheni commented on packages/kndp/charts/kndp/templates/k8s-provider.yaml
> +  name: provider-kubernetes
@ca7alindev What's changed, why you resolved it?
I asked to use helm templates for generate names of resources.

2023-12-28 11:59 UTC, web7evgheni commented on packages/meal/function/fn.go
> +func readMealResource(dynamicClient dynamic.Interface, ctx context.Context, group, version, resource, namespace string) (string, error) {
@ca7alindev Yes that i meant, you use parameters for single values, why you need this parameters, just remove them and use constants inside of function.

2023-12-28 11:59 UTC, web7evgheni commented on packages/meal/function/fn.go
> +									"host": "kndp.io",
@ca7alindev Why you resolve it? I asked to use environment variables, to be possible to configure host from helm chart, but you simply resolve issue?

2023-12-28 11:59 UTC, web7evgheni commented on packages/kndp/charts/kndp/templates/cm-meal.yaml
@ca7alindev Please move everything is related to meal into separate meal helm chart.

2023-12-28 14:10 UTC, ca7alindev commented
@web7evgheni please check

2023-12-28 16:04 UTC, web7evgheni requested changes

2023-12-28 16:04 UTC, web7evgheni commented on packages/meal/charts/meal/templates/functions.yaml
> +  package: ghcr.io/kndpio/kndp/package:0.1.0
@ca7alindev Why name is ghcr.io/kndpio/kndp/package:0.1.0 ? Shall comes from variables and has name of meal not?

2023-12-28 16:04 UTC, web7evgheni commented on packages/meal/charts/meal/values.yaml
@ca7alindev Please provide here default values, to be clear what is possible to change.

2023-12-28 16:04 UTC, web7evgheni commented on packages/meal/slack-notify/Dockerfile
> +RUN go build -o slack-cronjob
@ca7alindev Please rename it here also to slack-notify

2023-12-28 17:00 UTC, web7evgheni commented
@ca7alindev Please resolve this tow issues asap, because is too long already in development.

2023-12-29 09:00 UTC, ca7alindev commented
@web7evgheni please check

2024-01-02 13:29 UTC, web7evgheni requested changes

2024-01-02 13:29 UTC, web7evgheni commented on packages/meal/charts/meal/templates/functions.yaml
> +  package: ghcr.io/kndpio/kndp/meal:{{ .Values.function.image.tag | default .Chart.AppVersion }}
@ca7alindev Please put image name also into Values, as usual, why not?

2024-01-02 14:10 UTC, web7evgheni approved these changes

2024-01-02 14:10 UTC, merged