added a check of dueOverTime and employers votes in main function for…
kndpio/kndp pull request #156
Opened 2024-01-17 12:18 UTC by ca7alindev

… send slack results messages

2024-01-17 14:43 UTC, ca7alindev commented
@web7evgheni please check

2024-01-18 13:32 UTC, web7evgheni requested changes

2024-01-18 13:32 UTC, web7evgheni commented on packages/meal/function/fn.go
> +	if currentTime.After(dueOrderTime) || len(employers) == len(realUsers) {
@ca7alindev Please use TIMESTAMP as discussed.
Please don't hesitate to ask again if you not understood what is required or what is idea.

2024-01-18 13:56 UTC, ca7alindev commented on packages/meal/function/fn.go
> +	if currentTime.After(dueOrderTime) || len(employers) == len(realUsers) {
@web7evgheni i just want to clarify where to use timestamp format, for example in Meal object like {dueOverTime="1257894000"}?
Currently i use 24h time format for readeability reasons and escaped from need to create another cronjob for patching dueOverTime with timestamps everyday.

2024-01-18 14:58 UTC, ca7alindev commented on packages/meal/function/fn.go
> +	if currentTime.After(dueOrderTime) || len(employers) == len(realUsers) {
@web7evgheni please check latest changes

2024-01-18 15:47 UTC, web7evgheni approved these changes

2024-01-18 15:47 UTC, merged