added environment create context parameter
kndpio/kndp pull request #39
Opened 2024-02-16 15:13 UTC by ca7alindev

2024-02-16 15:34 UTC, web7evgheni requested changes

2024-02-16 15:34 UTC, web7evgheni commented on cmd/kndp/environment/create.go
> +	Context  string `optional:"" short:"c" help:"Context where kndp resources will be installed."`
@ca7alindev "Kubernetes context where Environment will be created."

2024-02-16 15:34 UTC, web7evgheni commented on cmd/kndp/environment/create.go
> +		os.Exit(1)
@ca7alindev Move it to be near line where "err" is defined.

2024-02-16 15:34 UTC, web7evgheni commented on cmd/kndp/environment/create.go
> +	}
@ca7alindev Put it under else of "if c.Context == "" {"

2024-02-19 08:34 UTC, web7evgheni requested changes

2024-02-19 08:34 UTC, web7evgheni commented on cmd/kndp/environment/create.go
> +		fmt.Println("Installing crossplane ...")
@ca7alindev Did you check, it takes right context, because looks like it still takes default.

2024-02-19 08:41 UTC, ca7alindev commented on cmd/kndp/environment/create.go
> +		fmt.Println("Installing crossplane ...")
@web7evgheni, context is switched by  "config, err := config.GetConfigWithContext(c.Context)" if "--context" parameter is provided, otherwise default context is used for creating resources

2024-02-19 08:42 UTC, ca7alindev commented on cmd/kndp/environment/create.go
> +	config, err := config.GetConfigWithContext(c.Context)
Context updated here

2024-02-19 10:20 UTC, ca7alindev commented on cmd/kndp/environment/create.go
> +	config, err := config.GetConfigWithContext(c.Context)
@web7evgheni if is empty is using default current context

2024-02-19 13:02 UTC, web7evgheni requested changes

2024-02-19 13:02 UTC, web7evgheni commented on cmd/kndp/environment/create.go
> +			fmt.Println(err)
@ca7alindev Shall be fatal exit, because if is not created, we shall not continue.

2024-02-19 14:34 UTC, web7evgheni approved these changes

2024-02-19 14:34 UTC, merged