exit program without deleting the source cluster if error occur
kndpio/kndp pull request #68
Opened 2024-02-26 15:57 UTC by ca7alindev

2024-02-27 07:39 UTC, web7evgheni requested changes

2024-02-27 07:39 UTC, web7evgheni commented on cmd/kndp/environment/move.go
> +						time.Sleep(5 * time.Second)
@ca7alindev Hope you understand this is as hack, and can't be done like this in fail safe utilities like kndp.
Please make checks on configuration install level, where you have to check configuration health, and just after this continue with resources of configuration.

2024-02-27 07:39 UTC, web7evgheni commented on cmd/kndp/environment/move.go
> +				if labels != nil && labels["app.kubernetes.io/managed-by"] == "kndp" {
@ca7alindev Add this to resources request as filter by label, this looks not good.
Just imagine you working with k8s API like with SQL DB, do you select all rows from DB and filter them, or add some condition as SQL WHERE? I think second, here shall be same.

2024-02-27 13:33 UTC, web7evgheni requested changes

2024-02-27 13:33 UTC, web7evgheni commented on cmd/kndp/environment/move.go
> +
@ca7alindev to internal

2024-02-27 13:33 UTC, web7evgheni commented on cmd/kndp/environment/move.go
> +					outerLoopBreak = true
@ca7alindev Here you check just fist configuration health, next configs are not verified, please be more attentive.

2024-02-27 13:33 UTC, web7evgheni commented on cmd/kndp/environment/move.go
> +				Version:   paramsXRs.Spec.Versions[0].Name,
@ca7alindev All versions please.

2024-02-27 13:33 UTC, web7evgheni commented on cmd/kndp/environment/move.go
>  func (c *moveCmd) Run(ctx context.Context, logger *log.Logger) error {
@ca7alindev Please move all logic to internal package, in command remains just parameters parsing if is required.
Main cause for that is later usage by TUI and other commands.

2024-02-28 21:27 UTC, web7evgheni requested changes

2024-02-28 21:27 UTC, web7evgheni commented on internal/environment/move.go
> +}
@ca7alindev move this to kube package

2024-02-28 21:27 UTC, web7evgheni commented on cmd/kndp/environment/move.go
> +		logger.Info("Successfully moved Kubernetes resources to the destination cluster.")
@ca7alindev move all of this to environment package.

2024-02-29 07:55 UTC, ca7alindev commented on cmd/kndp/environment/move.go
> +		logger.Info("Successfully moved Kubernetes resources to the destination cluster.")
@web7evgheni, but this logic is already in environment package under cmd/kndp/environment

2024-02-29 13:33 UTC, web7evgheni requested changes

2024-02-29 13:33 UTC, web7evgheni commented on internal/kube/client.go
> +func CreateKubernetesClients(ctx context.Context, logger *logger.Logger, context string) *dynamic.DynamicClient {
@ca7alindev According to Go naming convention, please rename it to Context()
https://google.github.io/styleguide/go/best-practices#naming-conventions

2024-02-29 13:33 UTC, web7evgheni commented on cmd/kndp/environment/move.go
> +		logger.Info("Successfully moved Kubernetes resources to the destination cluster.")
@ca7alindev Please collect all this sources inside of single function in internal/environment/move.go and call it in command function, how we discussed, all model related sources shall be outside of controller.

2024-03-01 11:43 UTC, web7evgheni approved these changes

2024-03-01 11:43 UTC, merged