Kndp 54
kndpio/kndp pull request #74
Opened 2023-08-28 13:23 UTC by catalindev0ps

2023-08-28 13:32 UTC, web7evgheni commented on .github/workflows/releases.yaml
> +        run: cat build.txt | xargs -I{} bash -c '[ -d {}/charts -a -f {}/Dockerfile ] && chart_name=$(basename $(dirname {}/charts/*/Chart.yaml)) && chart_version=$(helm search repo kndp --versions |
@catalindev0ps Not sure how it works, could you explain?

2023-08-28 14:01 UTC, catalindev0ps commented on .github/workflows/releases.yaml
> +        run: cat build.txt | xargs -I{} bash -c '[ -d {}/charts -a -f {}/Dockerfile ] && chart_name=$(basename $(dirname {}/charts/*/Chart.yaml)) && chart_version=$(helm search repo kndp --versions |
if $incremented is null, that means no charts founded in kndp repo that matching with release branch version, then a new release with release branch version will be deployed, in case that we create a new release with major version (2.0.0), then all charts will receive this new version, that's the current logic.

2023-08-28 14:13 UTC, web7evgheni requested changes

2023-08-28 14:13 UTC, web7evgheni commented on packages/kndp/Dockerfile
@catalindev0ps Please remove this changes from PR

2023-08-29 08:24 UTC, web7evgheni approved these changes

2023-08-29 08:24 UTC, merged