added interactive crossplane configuration apply
kndpio/kndp pull request #8
Opened 2024-02-01 14:30 UTC by ca7alindev

2024-02-01 15:06 UTC, web7evgheni requested changes

2024-02-01 15:06 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +	items, _ := GetResources(dynamicClient, ctx, "apiextensions.crossplane.io", "v1", "compositeresourcedefinitions", "")
@ca7alindev Idea was to list just resources which was in applied configuration, not all from environment.

2024-02-01 15:06 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +func GetResources(dynamic dynamic.Interface, ctx context.Context, group string, version string, resource string, namespace string) ([]unstructured.Unstructured, error) {
@ca7alindev Reduce amount of incoming parameters using struct

2024-02-01 15:06 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +	pterm.Success.Println("Crossplane upgrade completed successfully.")
@ca7alindev Why Crossplane, you applied KNDP configuration, not?

2024-02-01 15:06 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +		fmt.Println("No values selected.")
@ca7alindev No sense, to inform user about what he did, please delete this message.

2024-02-01 15:06 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +	form := huh.NewForm(
@ca7alindev Before display list, please ask user if he wants to create resources from applied configuration.

2024-02-01 15:06 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +			"packages": []string{c.Link},
@ca7alindev Here is a problem, when you will apply, previous configurations will be removed, because this is array, and configurations which is previous values is not in current upgrade values.

2024-02-01 15:13 UTC, ca7alindev commented on cmd/kndp/configuration/apply.go
> +			"packages": []string{c.Link},
@web7evgheni  I have already tested this problem, the last applied configurations are preserved

2024-02-02 14:21 UTC, web7evgheni requested changes

2024-02-02 14:21 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +func GetResources(p ResourceParams) ([]unstructured.Unstructured, error) {
@ca7alindev Please move it into internal package, eg. internal/kube/get.go and better to name it GetKubeResources, because as understand GO convention, public functions shall starts from upper case, but private from lower case.

2024-02-02 14:21 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +
@ca7alindev Please move helm client preparing into AfterApply of main package.

2024-02-02 14:21 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +func applyConfiguration(Link string, config *rest.Config) {
@ca7alindev Please move this function to internal/configuration/apply.go and rename to ApplyConfiguration

2024-02-02 14:21 UTC, web7evgheni commented on cmd/kndp/configuration/configuration.go
> +}
@ca7alindev to main module

2024-02-02 14:21 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +	}
@ca7alindev Why we need all this conditions, simple make by range over selected items, if it empty, range simple will not be executed, and program will continue.

2024-02-02 14:36 UTC, ca7alindev commented on cmd/kndp/configuration/apply.go
> +	if createResource {
@web7evgheni  At line 124 from selected option "Value(&createResource)"

2024-02-02 14:42 UTC, ca7alindev commented on cmd/kndp/configuration/apply.go
> +	}
@web7evgheni Because in case of empty xrds, list of options will still be displayed with no options to select

2024-02-02 14:57 UTC, web7evgheni requested changes

2024-02-02 14:57 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +type ConfigurationRevisions struct {
@ca7alindev Please name it to ConfigurationRevision, because is single object type, not list.

2024-02-02 14:58 UTC, web7evgheni requested changes

2024-02-02 14:58 UTC, web7evgheni commented on cmd/kndp/configuration/apply.go
> +		image := &ConfigurationRevisions{}
@ca7alindev Name it to eg. configRev, why image?

2024-02-02 16:30 UTC, web7evgheni approved these changes

2024-02-02 16:30 UTC, merged